setting:
  basicSetting:
    completionTone: 1 #是否开启完成提示音，0为关闭，1为开启
    colorLog: 1 #是否开启彩色日志，0为关闭，1为开启，如果控制台乱码可以尝试改为0关闭
    logOutFileSw: 1 #是否开启日志文件输出，0为关闭，1为开启
    logLevel: "INFO" #日志类型，一般INFO即可
    logModel: 0 #日志输出模式，0为以视频提交学时为单位进行日志输出，1为以课程信息为单位进行输出
    ipProxySw: 0 #是否开启IP代理，0代表关闭，1代表开启，开启后一定要子当前启动目录下创建ip.txt这个ip池文件，里面填写对应的代理IP即可，一行一个。注意，代理的IP一定要支持Https
  aiSetting:
    aiType: "TONGYI" #智普：CHATGLM、星火：XINGHUO、通义千问：TONGYI、豆包：DOUBAO、ChatGPT：OPENAI、其他模型：OTHER
    aiUrl: "" #默认不填，除非你用的不是上面所指明的AI模型，比如ChatGPT
    model: "" #AI模型，不填则使用yatori默认选择的模型，如果你用的豆包则必填并且填的是接入点ID非模型名称，比如ep-2024xxxxx
    API_KEY: "" #AI平台对应的apikey
  apiQueSetting:
    url: "http://localhost:8083" # 外部题库对接接口，用于外部对接题库操作，用于填写对应题库服务端url链接，使用时请严格遵循请求规范，对接请求规范请转至官方文档：https://yatori-dev.github.io/yatori-docs/bank-interface-api/docs.html

users:
  - accountType: "YINGHUA" #平台类型，英华学堂：YINGHUA、仓辉：CANGHUI、学习公社：ENAEA、学习通：XUEXITONG、重庆工业学院：CQIE
    url: "url" #对应平台的url链接,学习公社、CQIE、学习通可以不用填且可以直接把这一行去掉
    account: "账号" #账号
    password: "密码" #密码
    overBrush: 0 #覆刷模式，目前只支持英华，0代表关闭，1代表开启
    coursesCustom:
      videoModel: 1 #刷视频模式，0代表不刷，1代表普通模式，2代表暴力模式
      autoExam: 0 #是否自动考试，0代表不考试，1代表AI考试,2代表外部题库对接考试
      examAutoSubmit: 1 #是否考完试自动提交试卷，0代表不自动交卷，1代表自动交卷
      includeCourses: []  #include和exclude填一个即可，include代表只有这里面的课程才刷，填课程名称，比如["xxxx","xxxx"]
      excludeCourses: []  #include和exclude填一个即可，exclude代表除了这里面的课程其他都刷，填课程名称，比如["xxxx","xxxx"]
# 添加多个账号的时候像下面这样接着添加多个用户信息就行
  # - accountType: "YINGHUA"
  #   url: "url"
  #   account: "账号" 
  #   password: "密码"
  #   coursesCustom:
  #     videoModel: 1 
  #     autoExam: 0 
  #     examAutoSubmit: 1 
  #     includeCourses: []  
  #     excludeCourses: []  
  # - accountType: "YINGHUA"
  #   url: "url"
  #   account: "账号" 
  #   password: "密码"
  #   coursesCustom:
  #     videoModel: 1 
  #     autoExam: 0 
  #     examAutoSubmit: 1 
  #     includeCourses: []  
  #     excludeCourses: []  
# 更多详细配置文件说明请参考官方文档：https://yatori-dev.github.io/yatori-docs/yatori-go-console/docs.html